services:
  postgres:
    image: postgres:17
    container_name: contacomigo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openfinance_network

volumes:
  postgres_data:

networks:
  openfinance_network:
    driver: bridge
