services:
  api:
    build: .
    container_name: "mini_banco"
    ports:
      - "3050:3050"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mini_banco_central
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - .:/app
    restart: always
  
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5445:5432"
    environment:
      POSTGRES_DB: mini_banco_central
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    
volumes:
  pgdata:

